# NumPy Exercises


In [ ]:
import numpy as np
import string

## Array Creation

NumPy supports a variety of methods for array creation.

In [ ]:
# How would you create a one dimensional NumPy array of the numbers from 10 to 100, counting by 10?
one_dimension = np.arange(10, 101, 10)
one_dimension

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
# How could you do the same thing with a standard Python range and a list?
list1 = list(range(10, 101, 10))
list1

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [ ]:
# What does np.array() do (no arguments passed to constructor).  Guess:  exception?   Yes
# np.array()

In [ ]:
# How might you construct a NumPy array of capital letters (A-Z)
capital_letters = np.array(list(string.ascii_uppercase))
capital_letters

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [ ]:
# How would you create a ten-element array of all zeros?
zeros = np.zeros(10)

# Of all ones?
ones = np.ones(10)

In [ ]:
# What is the default data dype for the np.zeros function?
# float64

In [ ]:
# How can you create an array of 10 random integers?
random_integers = np.random.randint(0, 100, size=10)
random_integers

array([32,  3, 74, 34, 29, 80,  4, 62, 81, 14])

In [ ]:
# How can you create a normal distribution of 10 numbers, centered on 5?
# Note, the 1 in center represents mu, size of STD DEV, and is arbitrary.
normal_distribution = np.random.normal(loc=5, scale=1, size=10)
normal_distribution

array([4.11237631, 3.56449012, 6.29446317, 4.83319929, 4.614756  ,
       5.91131753, 5.46277964, 4.18730805, 5.70650218, 6.15496098])

In [ ]:
# How can you create an array of 10 random numbers in the range 0 - 1?
random_numbers = np.random.rand(10)
random_numbers

array([0.11787614, 0.04243384, 0.67879187, 0.61063655, 0.12410831,
       0.88267847, 0.00649909, 0.08886217, 0.28928017, 0.88538113])

# Multidimensional arrays


In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
array = np.arange(1, 13).reshape(3, 4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
array[1,2]

7

In [ ]:
array.ndim

2

In [ ]:
array.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
array.shape
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x = array
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x[0,0] = 42
array

array([[42,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Create a 3x4 array of random integers between 1 and 10
random_integers = np.random.randint(1, 11, size=(3, 4))
random_integers

array([[5, 2, 1, 2],
       [2, 1, 9, 3],
       [1, 3, 1, 6]])

In [ ]:
# ... or:
arr = np.random.randint(1,11,12).reshape(3,4)
arr

array([[2, 6, 4, 4],
       [7, 6, 5, 2],
       [4, 9, 6, 1]])

In [ ]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
z_list = [z for z in range(0,5)]
y_list = [z_list for y in range(0,4)]
x_list = [y_list for x in range(0,3)]

x_array = np.array(x_list)
y_array = np.array(y_list)
z_array = np.array(z_list)

In [ ]:
x_array.shape

(3, 4, 5)

In [ ]:
# What is the value of x_array.ndim?
x_array.ndim

3

In [ ]:
# Given the following:
arr = np.arange(0,6).reshape(2,3)
arr
# How could you convert it to an array that looks like
# array([[0,3], [1,4], [2,5]))
# My answer either arr.transpose() or arr.T
(arr.transpose() == arr.T).all()
# Note difference is mutablity?  NO!  Both return a view.  Need to copy.
# arr.transpose()


True

In [ ]:
four_by_five = np.arange(1, 21).reshape(4,5)
four_by_five

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# Write an exoression to return the first row
four_by_five[0]

array([1, 2, 3, 4, 5])

In [ ]:
# Write an exoression to return the last row
four_by_five[-1]

array([16, 17, 18, 19, 20])

In [ ]:
# What does four_by_five[2,3] return?  My answer, 14 (scalar)
four_by_five[2,3]

14

In [ ]:
# What does four_by_five[3,2] return?  My answer, 18 (scalar)
four_by_five[3,2]

18

In [ ]:
# How could you return the first column?  It will be a (four-element array ending with 16.) My answer four_by_five[:,0]
four_by_five[:,0]

array([ 1,  6, 11, 16])

In [ ]:
# What does four_by_five[:, 2:4] return?
# My answer the last two columns -- wrong, third and fourth columns
four_by_five[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [ ]:
# What does four_by_five[:, 3:5] return?
four_by_five[:, 3:5]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [ ]:
# Write an expression to return the last two columns of the middle two rows.
four_by_five[1:3, 3:]

array([[ 9, 10],
       [14, 15]])

In [ ]:
one_dim = np.arange(1,6)
one_dim

array([1, 2, 3, 4, 5])

In [ ]:
# What would be the result of one_dim * 2
# My answer array([2, 4, 6, 8, 10])
one_dim * 2

array([ 2,  4,  6,  8, 10])

In [ ]:
# What would be the result of one_dim + np.arange(5, 0, -1)?
# My answer:  array([ 6,  6,  6,  6, 6])
one_dim + np.arange(5, 0, -1)

array([6, 6, 6, 6, 6])

In [ ]:
# How many zeros are in the array returned by one_dim - one_dim ?
# My answer: 5
one_dim - one_dim

array([0, 0, 0, 0, 0])

In [ ]:
# What is the result of one_dim > 2 ?
# My answer:  array([F, F, T, T, T])  (abbreviated)
one_dim > 2

array([False, False,  True,  True,  True])

In [ ]:
# For NumPy arrays, logical operations are done with the operators "&" and "|",
# rather than the usual Python "and" and "or".  Given that, can you evaluate this expression?
# (one_dim > 4) | (one_dim == 1)
# My answer: array([True, False, False, False, True])
(one_dim > 4) | (one_dim == 1)

array([ True, False, False, False,  True])

In [ ]:
# What is the result of -one_dim?
# My answer array([-1, -2, -3, -4, -5])
-one_dim

array([-1, -2, -3, -4, -5])

In [ ]:
# np.absolute take the absolute value of each element.  Given that, what would the result be of the following expression:
# My answer 4,5
np.absolute(-(one_dim[3:]))

array([4, 5])

In [ ]:
# What is returned by one_dim.sum()?
# My answer: 15
one_dim.sum()

15

In [ ]:
# What is the value of one_dim.mean() ?
print(one_dim)
one_dim.mean() # The median!


[1 2 3 4 5]


3.0

In [ ]:
# Given the following...
arr = np.array([0., .5, 1.0, 1.5, 2.0]) * np.pi
arr

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [ ]:
# What are the "approximate" values for
# np.around(np.sin(arr), 0)
# My answer:  array(0, 1, 0, -1, 0)
np.around(np.sin(arr), 0)

array([ 0.,  1.,  0., -1., -0.])

In [ ]:
# What are the approximate values for
# np.around(np.cos(arr), 0)
# My answer:  array(1, 0, -1, 0, 1)
np.around(np.cos(arr), 0)

array([ 1.,  0., -1., -0.,  1.])

In [ ]:
# You're asked to save the following two arrays as is to a file, "data.npz". The arrays should be named as they are here in the file. How could you do it?
people = np.array(["John", "Jenniffer", "Helen", "Miryam"])
languages = np.array([2, 2, 1, 1])
# My answer np.savez("data.npz", people=people, languages=languages)
np.savez("data.npz", people=people, languages=languages)

In [ ]:
# How could you load the files again into two new variables, people2 and languages2
arrays = np.load("data.npz")
people2 = arrays["people"]
languages2 = arrays["languages"]
print(people2)
print(languages2)

['John' 'Jenniffer' 'Helen' 'Miryam']
[2 2 1 1]


In [ ]:
# Given
# arr = np.arange(1,13).reshape(3,4)
# Save it to a csv file, "myrray.csv".
arr = np.arange(1,13).reshape(3,4)
np.savetxt("myarray.csv", arr, delimiter=",")

In [ ]:
# How would you load it back into arr2?
# My guess: arr2 = np.loadtxt("myarray.csv", delimiter=",")
arr2 = np.loadtxt("myarray.csv", delimiter=",")
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [ ]:
# Given
lumberjack = np.array("I'm a lumberjack and I'm OK I sleep all night and I work all day".split(" "))
lumberjack

array(["I'm", 'a', 'lumberjack', 'and', "I'm", 'OK', 'I', 'sleep', 'all',
       'night', 'and', 'I', 'work', 'all', 'day'], dtype='<U10')

In [ ]:
# How could you capitalize the first character of each string?
# Guessed np.capitalize(lumberjack) wrong
np.char.capitalize(lumberjack)

array(["I'm", 'A', 'Lumberjack', 'And', "I'm", 'Ok', 'I', 'Sleep', 'All',
       'Night', 'And', 'I', 'Work', 'All', 'Day'], dtype='<U10')

In [ ]:
# What would you expect the value of np.char.capitalize(lunberjack)[2] to be?
# My answer "Lumberjack"
np.char.capitalize(lumberjack)[2]

'Lumberjack'

In [ ]:
# How could you surround each string with an initial and final asterisk character (*)?
# Guessed add takes n arguments, wrong, need two arguments at a time
np.char.add(np.char.add("*", lumberjack), "*")

array(["*I'm*", '*a*', '*lumberjack*', '*and*', "*I'm*", '*OK*', '*I*',
       '*sleep*', '*all*', '*night*', '*and*', '*I*', '*work*', '*all*',
       '*day*'], dtype='<U12')

In [ ]:
# np.where can be used to make selections.  How can we use this to create a smaller array of those strings that have a length >= 5?
# My guess np.where(lumberjack, np.length(lumberjack) >= 5)  Way off.

In [ ]:
np.where(np.char.str_len(lumberjack) >=5)

(array([2, 7, 9]),)

In [ ]:
lumberjack[np.where(np.char.str_len(lumberjack) >=5)]

array(['lumberjack', 'sleep', 'night'], dtype='<U10')